// Code generated by protoc-gen-nano. DO NOT EDIT.
// source: validation.proto

package api

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	"context"
	"github.com/pthethanh/nano/grpc/client"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var _ = context.TODO

func (UnimplementedRegistrationServiceServer) ServiceDesc() *grpc.ServiceDesc {
	return &RegistrationService_ServiceDesc
}

func (UnimplementedRegistrationServiceServer) Name() string {
	return "RegistrationServiceServer"
}

func MustNewRegistrationServiceClient(ctx context.Context, addr string, opts ...grpc.DialOption) RegistrationServiceClient {
	return &registrationServiceClient{
		cc: client.MustNew(ctx, addr, opts...),
	}
}
